parameters:
#    gallery.example.class: sas\galleryBundle\Example

services:
#    gallery.example:
#        class: %gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
